feat: update version check script in release_and_publish workflow
The version check script in the GitHub Actions workflow 'release_and_publish.yml' has been updated. The shell for this step has been changed to PowerShell and the syntax of the script has been adjusted accordingly. This change ensures that an error is thrown if the CARGO_VERSION environment variable is blank, improving error handling during the release and publish process.

diff --git a/.github/workflows/release_and_publish.yml b/.github/workflows/release_and_publish.yml
--- a/.github/workflows/release_and_publish.yml
+++ b/.github/workflows/release_and_publish.yml
@@ -110,12 +110,13 @@ jobs:
       CARGO_VERSION: ${{ needs.extract-version.outputs.cargo_version }}
     steps:
       - name: Fail if version is blank
+        shell: powershell
         run: |
-          if "%CARGO_VERSION%"=="" (
-          echo Error: CARGO_VERSION is blank.
-          exit /b 1
-          )
-          echo Cargo version is %CARGO_VERSION%
+          if (-not $env:CARGO_VERSION) {
+          Write-Error "Error: CARGO_VERSION is blank."
+          exit 1
+          }
+          Write-Host "Cargo version is $env:CARGO_VERSION"
       - uses: actions/checkout@v3
       - name: Install Rust
         uses: actions-rs/toolchain@v1
